import nodemailer from 'nodemailer';
import config from '../config/index.js';
import { logger } from '../utils/logger.js';

const transporter = nodemailer.createTransport({
  host: config.email.host,
  port: config.email.port,
  secure: config.email.secure,
  auth: config.email.auth,
});

export async function sendNotification(editorial) {
  if (!editorial) {
    logger.warn('No editorial to notify about');
    return false;
  }

  logger.info(`Sending notification to ${config.email.notificationEmail}...`);

  const subject = `New Editorial Draft: ${extractTitle(editorial.content)}`;
  const htmlContent = generateEmailHTML(editorial);
  const textContent = editorial.content;

  try {
    const info = await transporter.sendMail({
      from: config.email.auth.user,
      to: config.email.notificationEmail,
      subject,
      text: textContent,
      html: htmlContent,
    });

    logger.info(`Email sent: ${info.messageId}`);
    return true;
  } catch (error) {
    logger.error('Failed to send email notification:', error.message);
    return false;
  }
}

function extractTitle(markdownContent) {
  const match = markdownContent.match(/^#\s+(.+)$/m);
  return match ? match[1] : 'Untitled Editorial';
}

function generateEmailHTML(editorial) {
  const { marked } = require('marked');

  const bodyHTML = marked.parse(editorial.content);

  return `
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <style>
    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif;
      line-height: 1.6;
      color: #333;
      max-width: 650px;
      margin: 0 auto;
      padding: 20px;
      background-color: #f9f9f9;
    }
    .container {
      background-color: white;
      padding: 30px;
      border-radius: 8px;
      box-shadow: 0 2px 4px rgba(0,0,0,0.1);
    }
    h1 { color: #2c3e50; border-bottom: 3px solid #3498db; padding-bottom: 10px; }
    h2 { color: #34495e; margin-top: 30px; }
    a { color: #3498db; text-decoration: none; }
    a:hover { text-decoration: underline; }
    .sources {
      margin-top: 40px;
      padding: 20px;
      background-color: #ecf0f1;
      border-radius: 5px;
    }
    .footer {
      margin-top: 30px;
      padding-top: 20px;
      border-top: 1px solid #ddd;
      font-size: 0.9em;
      color: #777;
    }
  </style>
</head>
<body>
  <div class="container">
    ${bodyHTML}

    <div class="sources">
      <h3>📚 Sources</h3>
      <ul>
        ${editorial.sources.map(s => `
          <li><a href="${s.link}">${s.title}</a> (Score: ${s.score.toFixed(2)})</li>
        `).join('')}
      </ul>
    </div>

    <div class="footer">
      <p>Generated by <strong>Nervegna Editorial Engine</strong></p>
      <p>File: <code>${editorial.filename}</code></p>
      <p>Timestamp: ${new Date().toLocaleString()}</p>
    </div>
  </div>
</body>
</html>
  `;
}
